apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: mernstack
spec:
  type: LoadBalancer
  selector:
    app: frontend-pod
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
