# This is a deployment file for deploying UI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mernstack
  author: Vikas
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend-pod
    spec:
      containers:
        - name: frontend-container
          image: mongo-express:latest
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-pass
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-service-name
          resources:
            limits:
              memory: "100Mib"
              cpu: "150m"
            requests:
              memory: "150Mib"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 8081
              initialDelaySeconds: 30
              periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8081
              initialDelaySeconds: 30
              periodSeconds: 5
