apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: mernstack
  name: mongo-express-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
