apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db
  namespace: mernstack
  labels:
    app: mongo-app
    author: vikas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb-pod
  template:
    metadata:
      name: mongo-db
      labels:
        app: mongodb-pod
    spec:
      containers:
        - name: mongodb-container
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-volume
          # resources:
          #   limits:
          #     memory: "512Mi"
          #     cpu: "500m"
          #   requests:
          #     memory: "1Gi"
          #     cpu: "1"
          # livenessProbe:
          #   exec:
          #     command:
          #       - mongo
          #       - --host
          #       - localhost
          #       - --eval
          #       - "db.runCommand({ ping: 1})"
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          # readinessProbe:
          #   exec:
          #     command:
          #       - mongo
          #       - --host
          #       - localhost
          #       - --eval
          #       - "db.runCommand({ ping: 1 })"
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-pass

      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-pvc
