apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mernstack
spec:
  type: ClusterIP
  selector:
    app: mongodb-pod
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
